name: static-version-watch
on:
  workflow_call:
  workflow_dispatch:
      
permissions:
  contents: read
  pull-requests	: write
  id-token: write

jobs:
  static-version-watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse static.json
        id: static
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const path = require("path");
            const staticConfig = JSON.parse(fs.readFileSync("./static.json", "utf8"));
            const {
              generator,
              version
            } = staticConfig._static;
            // If there isn't a version, the respository is always using the default branch
            if (!version) return null;
            let nextVersion = null;
            try {
              nextVersion = parseInt(version.split(".")[0].replace("v", "")) + 1;
            } catch (e) {
              console.log("Error parsing version", e);
              return;
            }
            const [owner, repo] = generator.split("/");
            const response = github.rest.repos.getBranch({
              owner,
              repo,
              branch: nextVersion
            });
            console.log(nextVersion, response);
